import { test, expect } from "@playwright/test";

test("test", async ({ page }) => {
  await page.goto("http://127.0.0.1:8000/login");
  await page.getByPlaceholder("Masukkan Username").click();
  await page.getByPlaceholder("Masukkan Username").fill("admin");
  await page.getByPlaceholder("Masukkan Password").click();
  await page.getByPlaceholder("Masukkan Password").fill("admin123");
  await page.getByRole("button", { name: "Masuk" }).click();
  await page.getByRole("link", { name: " Pasien" }).click();
  await page.getByRole("link", { name: " Tambah Pasien" }).click();
  await page.getByText("Nama Pasien Jenis Kelamin").click();
  await page.getByLabel("Nama Pasien").click();
  await page.getByLabel("Nama Pasien").fill("alivia pertiwi");
  await page.getByLabel("Nama Pasien").press("Enter");
  await page.getByLabel("Jenis Kelamin").selectOption("P");
  await page.getByLabel("Agama").selectOption("Islam");
  await page.getByLabel("Alamat").click();
  await page.getByLabel("Alamat").fill("jalan cimahi\n");
  await page.getByLabel("Tanggal Lahir").fill("2025-01-14");
  await page.getByLabel("Usia").click();
  await page.getByLabel("Usia").fill("19");
  await page.getByLabel("Usia").press("Enter");
  await page.getByLabel("Nomor Telepon").click();
  await page.getByLabel("Nomor Telepon").fill("0987688");
  await page.getByLabel("Nama Kepala Keluarga").click();
  await page.getByLabel("Nama Kepala Keluarga").fill("67899889");
  await page.getByLabel("Hubungan Keluarga").click();
  await page.getByLabel("Hubungan Keluarga").fill("adik");
  await page.getByRole("button", { name: "Simpan" }).click();
});
